### ISSUE TITLE
Unexpected token error upon running gulp command and using babelify/reactify with JSX

### ISSUE THREAD

**Issue by brownty47** [brownty47/Portfolio#1]
On `gulp` from shell encountering `error  Parsing error: Unexpected token <` for all js files with jsx in them. I understand I know that browserify is not transforming it, I am just not sure why it is not.

The console shows 
    bundle.js:30695 Uncaught ReferenceError: jQuery is not defined
    at Object.185../components/homepage (http://localhost:9005/scripts/bundle.js:30695:12)
    at s (http://localhost:9005/scripts/bundle.js:1:254)
    at e (http://localhost:9005/scripts/bundle.js:1:425)
    at http://localhost:9005/scripts/bundle.js:1:443185../components/homepage @ bundle.js:30695s @ bundle.js:1e @ bundle.js:1(anonymous function) @ bundle.js:1

which does not make sense to me. I am not using any jquery so not sure why this is throwing undefined.

**Comment by brownty47** [comment]
Stupid error...fixed render in main.js
```JSX
React.render(<Home />, document.getElementById('app'));
```
to
```JSX
ReactDOM.render(<Home />, document.getElementById('app'));
```
